name: use-self-hosted-runner

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: none # [ main ]
  pull_request:
    branches: none # [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Use any of the labels of the selfhosted runner that the job will run on
    runs-on:  self-hosted # my-runner # ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5

      # Output environment details
      - name: Output environment details
        shell: bash
        run: |-
          echo "Kernel: $(uname -s) - $(uname -r)"
          echo "Machine: $(uname -m) - $(uname -o)"
          echo "Runner Name: '${{ runner.name }}'"
          echo "Runner OS: ${{ runner.os }}"
          echo "Runner ARCH: ${{ runner.arch }}"
