# This is a basic workflow to help you get started with Actions
name: Basic workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo "Hello, world! from ${{ github.actor }}."

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "Current branch is ${{ github.ref }}."
          echo "secrets.GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}" 
          echo "secrets.MY_SECRET:  ${{ secrets.MY_SECRET }}" 
          echo "vars.MY_VAR:  ${{ vars.MY_VAR }}"
          echo Add other actions to build,
          echo test, and deploy your project.

     # Show the files in the repo in a tree structure
      - name: Show tree
        run: tree

  # Output the entire context
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: echo "${{ toJSON(github) }}"
  
  logs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # To see the debug message in action, we can rerun the workflow job with debug logging enabled. 
      # In the workflow summary, click Re-run jobs | Re-run all jobs, select Enable debug logging, and click Re-run jobs (as shown in Figure 2.21):
      - run: |
          echo "::debug::This is a debug message."
          echo "::notice::This is a notice message."
          echo "::warning::This is a warning message."
          echo "::error::This is an error message."

          