# Examples of events, activity types & filters
name: Basic workflow

# Controls when the workflow will run
on:
  # Allows you running this workflow manually from the Actions tab
  workflow_dispatch:
  
    #Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    # Sequence of patterns matched against refs/tags: https://docs.github.com/en/actions/reference/workflows-and-actions/workflow-syntax#example-including-branches-and-tags
    tags:
     - v2
     - v1.*
    paths:
      - '**.js'

  pull_request:
    branches:
       - main
       - 'mona/octocat'
       - 'releases/**'

jobs:
  # This workflow contains a single job called "build"
  demo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"