name: Issue events handler
on: 
  # https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#issues
  issues:
    types: [opened, edited, milestoned]

jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"
      