# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Nodejs CI

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    # DIDN'T WORK!!! -> supplied src later in npm calls
    # defaults:
    # run:
    #     working-directory: src # move to where the source is

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      # https://github.com/marketplace/actions/setup-node-js-environment
      uses: actions/setup-node@v5
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: src/package-lock.json
    - run: npm ci ./src # run from src folder
    - run: npm run build --if-present ./src # run from src folder
    - run: npm --prefix src test # run test script from /src folder
    
    - name: Upload artifacts # demo on how to upload artifacts
      uses: actions/upload-artifact@v4 # https://github.com/actions/upload-artifact
      with:
        name: deploy-files
        path: |
          src
          node_modules
          package.json 

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deployed... "
